In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "I am a good boy",
        "I am a good developer",
        "understand the meaning of words",
        "your videos are good",]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

### In the above sent list there is some 4 and some 5 words in a sentance , here we have to convert into same number of words in each line.then only its possiable to get train by RNN

## Define the vocabulary size 

In [4]:
voc_size = 10000

In [5]:
### One Hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3231, 7780, 9953, 7878],
 [3231, 7780, 9953, 1057],
 [3231, 9657, 9953, 3047],
 [7287, 8518, 4987, 7014, 9161],
 [7287, 8518, 4987, 7014, 3397],
 [1027, 3231, 5500, 9953, 1864],
 [7315, 5630, 9729, 7014]]

In [6]:
## word Embedding Representation 
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
# setting the maximum words in that sent
# "pre" is used to add number of 0's in which sentance have less words  
# if we use "post" we get 0's at last
sent_length = 6
embedded_docs = pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0 3231 7780 9953 7878]
 [   0    0 3231 7780 9953 1057]
 [   0    0 3231 9657 9953 3047]
 [   0 7287 8518 4987 7014 9161]
 [   0 7287 8518 4987 7014 3397]
 [   0 1027 3231 5500 9953 1864]
 [   0    0 7315 5630 9729 7014]]


In [9]:
# feature representation 
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim = dim,input_length = sent_length))
model.compile('adam','mse')

d:\DL_project\envvv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
import numpy as np
model(np.array(embedded_docs))
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 6, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step


array([[[-0.04167787, -0.04363951, -0.00330335, -0.00953857,
         -0.03316798,  0.01859939,  0.03509618, -0.02415799,
          0.01365766, -0.03513557],
        [-0.04167787, -0.04363951, -0.00330335, -0.00953857,
         -0.03316798,  0.01859939,  0.03509618, -0.02415799,
          0.01365766, -0.03513557],
        [-0.04488099,  0.00044056,  0.00469881,  0.02169276,
          0.01929224,  0.01963811,  0.0305552 ,  0.03006304,
         -0.02553024,  0.04902111],
        [-0.02210838, -0.04600128, -0.01953545,  0.00590451,
         -0.04137316,  0.0265711 ,  0.00721132,  0.01776012,
         -0.04594419,  0.03837873],
        [-0.03330108,  0.04359995, -0.03832207,  0.03170177,
          0.02097932, -0.03163859,  0.00990622, -0.01990794,
          0.0494942 , -0.02877733],
        [ 0.01379276,  0.04859653, -0.01674252,  0.00968216,
         -0.04827837, -0.03368753, -0.04067133, -0.02014603,
          0.01319624,  0.00956569]],

       [[-0.04167787, -0.04363951, -0.00330335, -0